In [38]:
import numpy as np
import math
from math import pi, sin, cos

size = 6
conv_size = 2 * size + 1
different_range = pi*4/3
movement=10
result = []
grad=pi/6

In [39]:
conv = np.array([list(map(lambda x: x if abs(x) <= different_range / 2 else 0,
                              list(map(lambda x: x if x < pi else x - 2 * pi,
                                       [(0 if x - size == 0 and y - size == 0
                                         else (
                                                  -pi / 2 if x - size == 0 and y - size > 0
                                                  else (
                                                      pi / 2 if x - size == 0 and y - size < 0
                                                      else (-math.atan(
                                                          (y - size) / (
                                                                  x - size)) if x - size > 0
                                                            else pi - math.atan(
                                                          (y - size) / (
                                                                  x - size)))))
                                              - grad + 4 * pi) % (2 * pi)
                                        for x in range(conv_size)])))) for y in
                     range(conv_size)])

In [40]:
conv=(conv*180/pi).astype('int')

In [41]:
print(conv)

[[ 104   99   93   86   78   69   60   50   41   33   26   20   14]
 [ 110  104   98   90   81   71   60   48   38   29   21   14    9]
 [ 116  111  104   96   86   74   60   45   33   23   14    8    3]
 [   0  119  113  104   93   78   60   41   26   14    6    0   -3]
 [   0    0    0  116  104   86   60   33   14    3   -3   -8  -11]
 [   0    0    0    0    0  104   60   14   -3  -11  -15  -18  -20]
 [   0    0    0    0    0    0    0  -29  -29  -29  -29  -29  -29]
 [   0    0    0    0    0    0 -119  -75  -56  -48  -44  -41  -39]
 [   0    0    0    0    0    0 -119  -93  -75  -63  -56  -51  -48]
 [   0    0    0    0    0    0 -119 -101  -86  -75  -66  -60  -56]
 [   0    0    0    0    0    0 -119 -105  -93  -83  -75  -68  -63]
 [   0    0    0    0    0    0 -119 -108  -98  -89  -81  -75  -69]
 [   0    0    0    0    0    0 -119 -110 -101  -93  -86  -80  -75]]
